spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#zuul 路由配置可以省略，缺省以服务 id 作为访问路径
zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

  retryable: true
  
#ribbon重试参数设置
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetriesNextServer: 1
#  MaxAutoRetries: 1

#zuul + hystrix 熔断测试
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
# zuul + hystrix dashboard 监控 
# 暴露 hystrix.stream 监控端点          
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream